### PR TITLE
[PR] Feature/issue 282  new feature bilateral relations

### PR DESCRIPTION
**Pull request by lduf**
### Description
Add bilateral relations.

## Commands

Yuo must run the following : 

```
composer update
php artisan migrate
php artisan lists:update ListRelation --seed
```

## Issues fixed
List of related issues that are fixed by this PR :

Fix :
- #282 

### Checklist
- [ ] Compiling
- [ ] Code factoring (comments, indent...)
- [ ] Documentation (net4p Doc, Readme...)

### Feature Checklist
- [ ] Cytoscape
- [ ] Person/Index
- [ ] Person/Filter
- [ ] Person/Create
- [ ] Person/Edit
- [ ] Person/Delete
- [ ] Relation/Index
- [ ] Relation/Filter
- [ ] Relation/Create
- [ ] Relation/Edit
- [ ] Relation/Delete
- [ ] Duplicates/Index
- [ ] Duplicates/Filter
- [ ] Duplicates/Create
- [ ] Duplicates/Edit
- [ ] ManageList/Delete
- [ ] ManageList/Create
- [ ] ManageList/Edit
- [ ] ManageField/Index
- [ ] ManageField/Create
- [ ] ManageField/Edit
- [ ] ManageField/Delete
- [ ] ApiList
- [ ] Crews
- [ ] Users

### CODE REVIEW

**Comment by mathisfchx** [comment]
```# php artisan migrate

   INFO  Running migrations.  

  2022_11_15_135936_create_command_runs_table ............................................................................ 184ms DONE
  2022_11_15_143153_duplicates ........................................................................................... 135ms DONE
  2022_11_18_154211_add_type_to_list_relations_table ..................................................................... 119ms DONE
  2022_11_21_111017_rename_relation_to_relation_id_to_links ............................................................ 1,044ms DONE```

**Comment by mathisfchx** [comment]
```
php artisan lists:update ListRelation --seed
Updating ListRelation
Seeding ListRelation
```

**Review by mathisfchx — APPROVED** [review]
🌍

**Review by mathisfchx — APPROVED** [review]
🌍

**Review by mathisfchx — APPROVED** [review]
🌍

**Comment by lduf** [comment]
Force push because memory leak leads to test failure

**Pull request merged**
